Export the Execution class
Otherwise I run into errors like this:

/usr/bin/ld: CMakeFiles/extensionapiplugin.dir/extensionapi.cpp.o: in function `QSharedPointer<KAsync::Private::Execution> QSharedPointer<KAsync::Private::Execution>::create<QSharedPointer<KAsync::Private::ExecutorBase> const&>(QSharedPointer<KAsync::Private::ExecutorBase> const&)':
/usr/include/qt5/QtCore/qsharedpointer_impl.h:445: undefined reference to `KAsync::Private::Execution::Execution(QSharedPointer<KAsync::Private::ExecutorBase> const&)'
/usr/bin/ld: CMakeFiles/extensionapiplugin.dir/extensionapi.cpp.o: in function `QtSharedPointer::ExternalRefCountWithContiguousData<KAsync::Private::Execution>::deleter(QtSharedPointer::ExternalRefCountData*)':
/usr/include/qt5/QtCore/qsharedpointer_impl.h:256: undefined reference to `KAsync::Private::Execution::~Execution()'
[ 91%] Built target kubetestrunner
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)

I assume this is because execution_p.h is now included from the async.h
header.